version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    network_mode: host
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: localhost
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    container_name: mysql
    network_mode: host
    volumes:
      - "./volumes/mysql/mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  echo:
    image: hashicorp/http-echo
    container_name: echo
    network_mode: host
    command:
      - -listen=:5678
      - -text="hello wolrd"

  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - "./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf"

  auth_proxy:
    image: quay.io/keycloak/keycloak-gatekeeper
    container_name: auth_proxy
    network_mode: host
    volumes:
      - "./volumes/keycloak-gatekeeper:/data/keycloak-gatekeeper"
    command:
      - --config=/data/keycloak-gatekeeper/config.yml
