version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "http://keycloak.local.com:8080/auth" # pointing it to wherever your nginx proxy is
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      JDBC_PARAMS: "useSSL=false"
      PROXY_ADDRESS_FORWARDING: "true"

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./volumes/mysql/mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  echo:
    image: hashicorp/http-echo
    container_name: echo
    command:
      - -listen=:5678
      - -text="hello wolrd"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 8080:8080 # keycloak port
    volumes:
      - "./configs/nginx/nginx.conf:/etc/nginx/nginx.conf"

  auth_proxy:
    image: quay.io/keycloak/keycloak-gatekeeper
    container_name: auth_proxy
    extra_hosts:
      - "keycloak.local.com:10.6.42.134"
    volumes:
      - "./configs/keycloak-gatekeeper:/data/keycloak-gatekeeper"
    command:
      - --config=/data/keycloak-gatekeeper/config.yml
