apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-example-local
  namespace: proxy
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    proxy-group: proxy-group-1
  servers:
  - hosts:
    - 'httpbin.example.local'
    port:
      name: http-httpbin
      number: 80
      protocol: http
    tls:
      httpsRedirect: true
  - hosts:
    - 'httpbin.example.local'
    port:
      name: https-httpbin
      number: 443
      protocol: https
    tls:
      mode: SIMPLE
      credentialName: httpbin-cert
