# Configuration for a stdio handler
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: newloghandler
  namespace: istio-system
spec:
  compiledAdapter: stdio
  params:
    severity_levels:
      warning: 1 # Params.Level.WARNING
    outputAsJson: false
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: newlog
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"warning"'
    timestamp: request.time
    variables:
      source: source.labels["app"] | source.workload.name | "unknown"
      source_ip: source.ip | ip("0.0.0.0")
      destination: destination.labels["app"] | destination.workload.name | "unknown"
      destination_ip: destination.ip | ip("0.0.0.0")
      destination_version: destination.labels["version"] | "unknown"
      origin_ip: origin.ip | ip("0.0.0.0")
      xff_ip: request.headers["x-forwarded-for"] | "0.0.0.0"
      real_ip: request.headers["x-real-ip"] | "0.0.0.0"
      request_host: request.host | "unknown"
      request_path: request.path | "unknown"
      responseCode: response.code | 0
      responseSize: response.size | 0
      latency: response.duration | "0ms"
    monitored_resource_type: '"UNSPECIFIED"'
---
# Rule to send logentry instances to a stdio handler
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: newlogstdio
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions:
   - handler: newloghandler
     instances:
     - newlog
---
