name: etcd3

data-dir: /etcd-data

# initial-cluster: etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
initial-cluster: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380

listen-peer-urls: http://0.0.0.0:2380
listen-client-urls: http://0.0.0.0:2379

initial-advertise-peer-urls: http://etcd3:2380
advertise-client-urls: http://etcd3:2379

# initial-cluster-state: existing
