apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  # Install Istio with `minimal` profile
  profile: minimal
  components:
    ingressGateways:
    - name: my-custom-istio-ingressgateway
      enabled: true
      namespace: proxy
      label:
        proxy-group: proxy-group-1
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        sds:
          enabled: true
    pilot:
      autoscaleEnabled: false
    prometheus:
      enabled: true
    grafana:
      enabled: true
    global:
      defaultPodDisruptionBudget:
        enabled: false
      proxy:
        accessLogFile: "/dev/stdout"
        accessLogEncoding: JSON
