apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  # Install Istio with `minimal` profile
  profile: minimal
  components:
    ingressGateways:
    - name: my-custom-istio-ingressgateway
      enabled: true
      label:
        proxy-group: proxy-group-1
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
    pilot:
      autoscaleEnabled: false
    global:
      defaultPodDisruptionBudget:
        enabled: false
