apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  # Install Istio with `minimal` profile
  profile: minimal
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
    pilot:
      autoscaleEnabled: false
