apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: vanhtuan0409@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
    - http01:
       ingress:
         serviceType: ClusterIP
---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: test.example.com
spec:
  secretName: tls-test.example.com
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - test.example.com
  - www.test.example.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io
