# for doubandb
# should include all configurable fields
server:
  zkservers:
    - localhost:2181
  zkpath: "/beansdb/test"
  listen: 0.0.0.0
  port: 7900
  webport: 7903
  threads: 4
  errorlog: ./volumes/beansdb/error.log
  accesslog: ./volumes/beansdb/access.log
  analysislog: ./volumes/beansdb/analysis.log
  hostname: 127.0.0.1
  staticdir: /tmp/var/lib/gobeansdb
mc:
  body_c_str: 0
hstore:
  data:
    flush_interval: 0
    flush_wake_str: 0
    no_gc_days: 0
  local:
    homes:
    - ./volumes/testdb
  htree:
    tree_height: 3
    tree_dump : 1
  hint:
    hint_no_merged: false
